In [2]:
import pandas as pd

In [38]:
course={
    "course_id":[401,402,403,404,408],
    "course_name":['BCA','BTECH','MCA','BCOM','MBA'],
    "course_fees":[20000,22000,21290,23435,28900],
    'course_duration':['3 years','4 years','2 years','3 years','2 years']
}

student={
    "std_id":[1,2,3,4,5,6,7,8],
    "name":['raj','ravi','riya','hardik','tanvi','renu','deepak','nihal'],
    "age":[20,22,21,24,22,27,28,25],
    "city":['indore','satna','katni','indore','maihar','bpl','jbp','satna'] ,
    "c_id":[401,402,405,401,402,403,404,407]
}
c_df=pd.DataFrame(course)
s_df=pd.DataFrame(student)

In [39]:
c_df

   course_id course_name  course_fees course_duration
0        401         BCA        20000         3 years
1        402       BTECH        22000         4 years
2        403         MCA        21290         2 years
3        404        BCOM        23435         3 years
4        408         MBA        28900         2 years

In [40]:
s_df

   std_id    name  age    city  c_id
0       1     raj   20  indore   401
1       2    ravi   22   satna   402
2       3    riya   21   katni   405
3       4  hardik   24  indore   401
4       5   tanvi   22  maihar   402
5       6    renu   27     bpl   403
6       7  deepak   28     jbp   404
7       8   nihal   25   satna   407

In [41]:
# inner
student_course=pd.merge(s_df,c_df,how='inner',left_on='c_id',right_on='course_id')

In [42]:
student_course

,std_id,name,age,city,c_id,course_id,course_name,course_fees,course_duration
0,1,raj,20,indore,401,401,BCA,20000,3 years
1,2,ravi,22,satna,402,402,BTECH,22000,4 years
2,4,hardik,24,indore,401,401,BCA,20000,3 years
3,5,tanvi,22,maihar,402,402,BTECH,22000,4 years
4,6,renu,27,bpl,403,403,MCA,21290,2 years
5,7,deepak,28,jbp,404,404,BCOM,23435,3 years

In [43]:
# inner join me agar left table aur right table me koi bhi column ka data same hota hai jaise ki dono me course id and c_id 
# ho to waha pe ham inner join use krte hai

In [44]:
# left join me sab kuch join hota hai jaise ki left table me jo jo bhi data hai vo sara righ vali table me dekhta hai aur agar value nahi hai to 
# null ho jaega

In [45]:
# left
student_course=pd.merge(s_df,c_df,how='left',left_on='c_id',right_on='course_id')
student_course

,std_id,name,age,city,c_id,course_id,course_name,course_fees,course_duration
0,1,raj,20,indore,401,401.0,BCA,20000.0,3 years
1,2,ravi,22,satna,402,402.0,BTECH,22000.0,4 years
2,3,riya,21,katni,405,NaN,NaN,NaN,NaN
3,4,hardik,24,indore,401,401.0,BCA,20000.0,3 years
4,5,tanvi,22,maihar,402,402.0,BTECH,22000.0,4 years
5,6,renu,27,bpl,403,403.0,MCA,21290.0,2 years
6,7,deepak,28,jbp,404,404.0,BCOM,23435.0,3 years
7,8,nihal,25,satna,407,NaN,NaN,NaN,NaN

In [46]:
# cross join me multiply hote hai

In [47]:
# right
student_course=pd.merge(s_df,c_df,how='right',left_on='c_id',right_on='course_id')
student_course

,std_id,name,age,city,c_id,course_id,course_name,course_fees,course_duration
0,1.0,raj,20.0,indore,401.0,401,BCA,20000,3 years
1,4.0,hardik,24.0,indore,401.0,401,BCA,20000,3 years
2,2.0,ravi,22.0,satna,402.0,402,BTECH,22000,4 years
3,5.0,tanvi,22.0,maihar,402.0,402,BTECH,22000,4 years
4,6.0,renu,27.0,bpl,403.0,403,MCA,21290,2 years
5,7.0,deepak,28.0,jbp,404.0,404,BCOM,23435,3 years
6,NaN,NaN,NaN,NaN,NaN,408,MBA,28900,2 years

In [48]:
# outer
student_course=pd.merge(s_df,c_df,how='outer',left_on='c_id',right_on='course_id')
student_course

,std_id,name,age,city,c_id,course_id,course_name,course_fees,course_duration
0,1.0,raj,20.0,indore,401.0,401.0,BCA,20000.0,3 years
1,4.0,hardik,24.0,indore,401.0,401.0,BCA,20000.0,3 years
2,2.0,ravi,22.0,satna,402.0,402.0,BTECH,22000.0,4 years
3,5.0,tanvi,22.0,maihar,402.0,402.0,BTECH,22000.0,4 years
4,6.0,renu,27.0,bpl,403.0,403.0,MCA,21290.0,2 years
5,7.0,deepak,28.0,jbp,404.0,404.0,BCOM,23435.0,3 years
6,3.0,riya,21.0,katni,405.0,NaN,NaN,NaN,NaN
7,8.0,nihal,25.0,satna,407.0,NaN,NaN,NaN,NaN
8,NaN,NaN,NaN,NaN,NaN,408.0,MBA,28900.0,2 years

In [49]:
# cross
student_course=pd.merge(s_df,c_df,how='cross')
student_course

,std_id,name,age,city,c_id,course_id,course_name,course_fees,course_duration
0,1,raj,20,indore,401,401,BCA,20000,3 years
1,1,raj,20,indore,401,402,BTECH,22000,4 years
2,1,raj,20,indore,401,403,MCA,21290,2 years
3,1,raj,20,indore,401,404,BCOM,23435,3 years
4,1,raj,20,indore,401,408,MBA,28900,2 years
5,2,ravi,22,satna,402,401,BCA,20000,3 years
6,2,ravi,22,satna,402,402,BTECH,22000,4 years
7,2,ravi,22,satna,402,403,MCA,21290,2 years
8,2,ravi,22,satna,402,404,BCOM,23435,3 years
9,2,ravi,22,satna,402,408,MBA,28900,2 years
10,3,riya,21,katni,405,401,BCA,20000,3 years
11,3,riya,21,katni,405,402,BTECH,22000,4 years
12,3,riya,21,katni,405,403,MCA,21290,2 years
13,3,riya,21,katni,405,404,BCOM,23435,3 years
14,3,riya,21,katni,405,408,MBA,28900,2 years
15,4,hardik,24,indore,401,401,BCA,20000,3 years
16,4,hardik,24,indore,401,402,BTECH,22000,4 years
17,4,hardik,24,indore,401,403,MCA,21290,2 years
18,4,hardik,24,indore,401,404,BCOM,23435,3 years
19,4,hardik,24,indore,401,408,MBA,28900,2 years
20,5,tanvi,22,maihar,402,401,BCA,20000,3 years
21,5,tanvi,22,maihar,402,402,BTECH,22000,4 years
22,5,tanvi,22,maihar,402,403,MCA,21290,2 years
23,5,tanvi,22,maihar,402,404,BCOM,23435,3 years
24,5,tanvi,22,maihar,402,408,MBA,28900,2 years
25,6,renu,27,bpl,403,401,BCA,20000,3 years
26,6,renu,27,bpl,403,402,BTECH,22000,4 years
27,6,renu,27,bpl,403,403,MCA,21290,2 years
28,6,renu,27,bpl,403,404,BCOM,23435,3 years
29,6,renu,27,bpl,403,408,MBA,28900,2 years
30,7,deepak,28,jbp,404,401,BCA,20000,3 years
31,7,deepak,28,jbp,404,402,BTECH,22000,4 years
32,7,deepak,28,jbp,404,403,MCA,21290,2 years
33,7,deepak,28,jbp,404,404,BCOM,23435,3 years
34,7,deepak,28,jbp,404,408,MBA,28900,2 years
35,8,nihal,25,satna,407,401,BCA,20000,3 years
36,8,nihal,25,satna,407,402,BTECH,22000,4 years
37,8,nihal,25,satna,407,403,MCA,21290,2 years
38,8,nihal,25,satna,407,404,BCOM,23435,3 years
39,8,nihal,25,satna,407,408,MBA,28900,2 years

In [ ]:
id , name , discription
id , name , age , salary , dep_id

In [51]:
department={
    "department_id":[101,102,103],
    "department_name":['SALES','FINANCE','IT'],
    "description":['data entry','stock market ','CS is IT ']   
}

d_df=pd.DataFrame(department)
employee={
    "emp_id":[401,402,403,404],
    "emp_name":['raj','ravi','riya','hardik'],
    "age":[20,22,21,24],
    'salary':[1000000,2000000,2054000,5485413],
    "dep_id":[101,102,103,102] 
}
e_df=pd.DataFrame(employee)

In [53]:
employee_details=pd.merge(e_df,d_df,how='inner',left_on="dep_id",right_on="department_id")
employee_details

,emp_id,emp_name,age,salary,dep_id,department_id,department_name,description
0,401,raj,20,1000000,101,101,SALES,data entry
1,402,ravi,22,2000000,102,102,FINANCE,stock market
2,403,riya,21,2054000,103,103,IT,CS is IT
3,404,hardik,24,5485413,102,102,FINANCE,stock market

In [54]:
employee_details=pd.merge(e_df,d_df,how='left',left_on="dep_id",right_on="department_id")
employee_details

,emp_id,emp_name,age,salary,dep_id,department_id,department_name,description
0,401,raj,20,1000000,101,101,SALES,data entry
1,402,ravi,22,2000000,102,102,FINANCE,stock market
2,403,riya,21,2054000,103,103,IT,CS is IT
3,404,hardik,24,5485413,102,102,FINANCE,stock market

In [55]:
employee_details=pd.merge(e_df,d_df,how='right',left_on="dep_id",right_on="department_id")
employee_details

,emp_id,emp_name,age,salary,dep_id,department_id,department_name,description
0,401,raj,20,1000000,101,101,SALES,data entry
1,402,ravi,22,2000000,102,102,FINANCE,stock market
2,404,hardik,24,5485413,102,102,FINANCE,stock market
3,403,riya,21,2054000,103,103,IT,CS is IT

In [56]:
employee_details=pd.merge(e_df,d_df,how='outer',left_on="dep_id",right_on="department_id")
employee_details

,emp_id,emp_name,age,salary,dep_id,department_id,department_name,description
0,401,raj,20,1000000,101,101,SALES,data entry
1,402,ravi,22,2000000,102,102,FINANCE,stock market
2,404,hardik,24,5485413,102,102,FINANCE,stock market
3,403,riya,21,2054000,103,103,IT,CS is IT

In [57]:
employee_details=pd.merge(e_df,d_df,how='cross')
employee_details

,emp_id,emp_name,age,salary,dep_id,department_id,department_name,description
0,401,raj,20,1000000,101,101,SALES,data entry
1,401,raj,20,1000000,101,102,FINANCE,stock market
2,401,raj,20,1000000,101,103,IT,CS is IT
3,402,ravi,22,2000000,102,101,SALES,data entry
4,402,ravi,22,2000000,102,102,FINANCE,stock market
5,402,ravi,22,2000000,102,103,IT,CS is IT
6,403,riya,21,2054000,103,101,SALES,data entry
7,403,riya,21,2054000,103,102,FINANCE,stock market
8,403,riya,21,2054000,103,103,IT,CS is IT
9,404,hardik,24,5485413,102,101,SALES,data entry
10,404,hardik,24,5485413,102,102,FINANCE,stock market
11,404,hardik,24,5485413,102,103,IT,CS is IT