In [2]:
import pandas as pd

In [20]:
students={
    "student_id":[1,2,3,4,5],
    "std_name":["John","Jane","Jim","Jill","Jack"],
    "std_age":[20,21,22,23,24],
    "city":["New York","Los Angeles","Chicago","Houston","Miami"],
    "course":["Math","Science","Science","English","Math"],
    "fee":[1000,2000,3000,4000,5000]
}

df=pd.DataFrame(students)
print(df)

   student_id std_name  std_age         city   course   fee
0           1     John       20     New York     Math  1000
1           2     Jane       21  Los Angeles  Science  2000
2           3      Jim       22      Chicago  Science  3000
3           4     Jill       23      Houston  English  4000
4           5     Jack       24        Miami     Math  5000

In [21]:
print(df['fee'].mean())

3000.0

In [22]:
print(df['fee'].sum())

15000

In [23]:
print(df['fee'].max())

5000

In [24]:
print(df['fee'].min())

1000

In [25]:
print(df['fee'].std())

1581.1388300841897

In [26]:
print(df['fee'].var())

2500000.0

In [27]:
print(df['fee'].median())

3000.0

In [28]:
df.groupby('course')['fee'].sum()

course
English    4000
Math       6000
Science    5000
Name: fee, dtype: int64

In [29]:
df.groupby('course')['fee'].min()

course
English    4000
Math       1000
Science    2000
Name: fee, dtype: int64

In [30]:
df.groupby('course')['fee'].mean()

course
English    4000.0
Math       3000.0
Science    2500.0
Name: fee, dtype: float64

In [31]:
df.groupby('course')['fee'].max()

course
English    4000
Math       5000
Science    3000
Name: fee, dtype: int64

In [32]:
df.groupby('city')['fee'].sum()

city
Chicago        3000
Houston        4000
Los Angeles    2000
Miami          5000
New York       1000
Name: fee, dtype: int64

In [33]:
df.groupby('city')['fee'].max()

city
Chicago        3000
Houston        4000
Los Angeles    2000
Miami          5000
New York       1000
Name: fee, dtype: int64

In [34]:
df.groupby('city')['fee'].var()

city
Chicago       NaN
Houston       NaN
Los Angeles   NaN
Miami         NaN
New York      NaN
Name: fee, dtype: float64

In [35]:
df.groupby('city')['fee'].mean()

city
Chicago        3000.0
Houston        4000.0
Los Angeles    2000.0
Miami          5000.0
New York       1000.0
Name: fee, dtype: float64

In [38]:
df.groupby('city')['fee'].std()

city
Chicago       NaN
Houston       NaN
Los Angeles   NaN
Miami         NaN
New York      NaN
Name: fee, dtype: float64

In [47]:
df.groupby('city')['fee'].agg({'sum','max','min','mean','count'})

               mean   min  count   sum   max
city
Chicago      3000.0  3000      1  3000  3000
Houston      4000.0  4000      1  4000  4000
Los Angeles  2000.0  2000      1  2000  2000
Miami        5000.0  5000      1  5000  5000
New York     1000.0  1000      1  1000  1000

In [48]:
df.groupby('std_age')['fee'].describe()

         count    mean  std     min     25%     50%     75%     max
std_age
20         1.0  1000.0  NaN  1000.0  1000.0  1000.0  1000.0  1000.0
21         1.0  2000.0  NaN  2000.0  2000.0  2000.0  2000.0  2000.0
22         1.0  3000.0  NaN  3000.0  3000.0  3000.0  3000.0  3000.0
23         1.0  4000.0  NaN  4000.0  4000.0  4000.0  4000.0  4000.0
24         1.0  5000.0  NaN  5000.0  5000.0  5000.0  5000.0  5000.0

In [51]:
df1=pd.read_csv("train.csv")

In [53]:
df1.head(0)

Empty DataFrame
Columns: [Row ID, Order ID, Order Date, Ship Date, Ship Mode, Customer ID, Customer Name, Segment, Country, City, State, Postal Code, Region, Product ID, Category, Sub-Category, Product Name, Sales]
Index: []

In [56]:
df1.groupby('Category')['Sales'].describe()

,count,mean,std,min,25%,50%,75%,max
Category,,,,,,,,
Furniture,2078.0,350.653790,501.489219,1.892,47.19,182.610,435.237,4416.174
Office Supplies,5909.0,119.381001,383.761427,0.444,11.76,27.360,79.470,9892.740
Technology,1813.0,456.401474,1116.818701,0.990,67.98,167.944,453.576,22638.480

In [57]:
df1.groupby('Category')['Sales'].agg({'sum','max','min','mean','count'})

                       mean    min  count          sum        max
Category
Furniture        350.653790  1.892   2078  728658.5757   4416.174
Office Supplies  119.381001  0.444   5909  705422.3340   9892.740
Technology       456.401474  0.990   1813  827455.8730  22638.480

In [59]:
df2=pd.read_excel("1.xls")

In [61]:
df2.head(0)

Empty DataFrame
Columns: [Row ID, Order ID, Order Date, Ship Date, Ship Mode, Customer ID, Customer Name, Segment, Country, City, State, Postal Code, Region, Product ID, Category, Sub-Category, Product Name, Sales, Quantity, Discount, Profit]
Index: []

[0 rows x 21 columns]

In [ ]:
df2.groupby('Category')['Profit'].agg({'sum','max','min','mean','count'})

                      mean        min  count          sum       max
Category
Furniture         8.699327 -1862.3124   2121   18451.2728  1013.127
Office Supplies  20.327050 -3701.8928   6026  122490.8008  4946.370
Technology       78.752002 -6599.9780   1847  145454.9481  8399.976

In [64]:
df2.groupby('City')['Profit'].agg({'sum','max','min','mean','count'})

                   mean       min  count        sum        max
City
Aberdeen       6.630000    6.6300      1     6.6300     6.6300
Abilene       -3.758400   -3.7584      1    -3.7584    -3.7584
Akron         -8.887410  -80.9955     21  -186.6356    66.5408
Albuquerque   45.292007   -5.6943     14   634.0881   138.3552
Alexandria    19.913644    0.0000     16   318.6183    83.2810
...                 ...       ...    ...        ...        ...
Woonsocket    19.669775   13.8915      4    78.6791    22.8900
Yonkers      184.517047 -264.9208     15  2767.7557  2400.9657
York         -20.433840  -50.8704      5  -102.1692    23.7742
Yucaipa       13.208000   13.2080      1    13.2080    13.2080
Yuma        -116.497725 -479.9880      4  -465.9909    48.7011

[531 rows x 5 columns]