In [2]:
import pandas as pd

In [7]:
CATEGORY=['A','B','C','D','A','B']
ser=pd.Categorical(CATEGORY)
ser

['A', 'B', 'C', 'D', 'A', 'B']
Categories (4, object): ['A', 'B', 'C', 'D']

In [8]:
ser.codes

array([0, 1, 2, 3, 0, 1], dtype=int8)

In [9]:
ser.categories

Index(['A', 'B', 'C', 'D'], dtype='object')

In [10]:
ser.ordered

False

In [11]:
my_order=['D','C','B','A']
ser=pd.Categorical(CATEGORY,ordered=True,categories=my_order)
ser

['A', 'B', 'C', 'D', 'A', 'B']
Categories (4, object): ['D' < 'C' < 'B' < 'A']

In [12]:
ser.codes

array([3, 2, 1, 0, 3, 2], dtype=int8)

In [13]:
ser.categories

Index(['D', 'C', 'B', 'A'], dtype='object')

In [14]:
ser.ordered

True

In [28]:
df=pd.DataFrame({
    'Category':pd.Categorical(['low','medium','high','medium','low']),
    'Value':[100,200,300,400,500]})
df

  Category  Value
0      low    100
1   medium    200
2     high    300
3   medium    400
4      low    500

In [29]:
new=df.sort_values(by='Category')
new

  Category  Value
2     high    300
0      low    100
4      low    500
1   medium    200
3   medium    400

In [30]:
df_high=df[df['Category']=='high']
df_high

  Category  Value
2     high    300

In [31]:
df_medium=df[df['Category']=='medium']
df_medium

  Category  Value
1   medium    200
3   medium    400

In [32]:
df_low=df[df['Category']=='low']
df_low

  Category  Value
0      low    100
4      low    500

In [36]:
df['Category']=df['Category'].replace({'low':'very low'})
df

   Category  Value
0  very low    100
1    medium    200
2      high    300
3    medium    400
4  very low    500

In [38]:
category_count=df['Category'].value_counts()
category_count

Category
very low    2
medium      2
high        1
Name: count, dtype: int64

In [40]:
df_encode=pd.get_dummies(df,columns=['Category'])
df_encode

   Value  Category_high  Category_very low  Category_medium
0    100          False               True            False
1    200          False              False             True
2    300           True              False            False
3    400          False              False             True
4    500          False               True            False

In [46]:
df_encode.astype(int)

   Value  Category_high  Category_very low  Category_medium
0    100              0                  1                0
1    200              0                  0                1
2    300              1                  0                0
3    400              0                  0                1
4    500              0                  1                0