In [3]:
import pandas as pd
data = {'Name' : ['Ajay','Vijay','Jay'],
        'Age' : [20,25,50],
        'Salary' : [500000,35467,23453]
}
df=pd.DataFrame(data)

In [4]:
def age_group(age):
    if age < 18:
        return 'minor'
    elif age >= 18:
        return 'adult'
    else:
        return 'senior'

In [6]:
df['age_group']=df['Age'].apply(age_group)

In [7]:
df['salary with bonus']=df['Salary'].apply(lambda x: x*1.10)
df

    Name  Age  Salary age_group  salary with bonus
0   Ajay   20  500000     adult           550000.0
1  Vijay   25   35467     adult            39013.7
2    Jay   50   23453     adult            25798.3

In [8]:
df['tax of salary']=df['Salary'].apply(lambda x: x*0.15)
df

    Name  Age  Salary age_group  salary with bonus  tax of salary
0   Ajay   20  500000     adult           550000.0       75000.00
1  Vijay   25   35467     adult            39013.7        5320.05
2    Jay   50   23453     adult            25798.3        3517.95

In [11]:
df2=pd.DataFrame({'a':[1,2,3],'b':[4,5,6]})

In [12]:
df2=df.applymap(lambda x: x*2)
df2

C:\Users\nepro\AppData\Local\Temp\ipykernel_6576\2979214628.py:1: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df2=df.applymap(lambda x: x*2)

         Name  Age   Salary   age_group  salary with bonus  tax of salary
0    AjayAjay   40  1000000  adultadult          1100000.0       150000.0
1  VijayVijay   50    70934  adultadult            78027.4        10640.1
2      JayJay  100    46906  adultadult            51596.6         7035.9

In [27]:
df3=pd.DataFrame({
    'Name':['Ajay Mishra','Vijay','Jay'],
    'Age':[20,25,50],
    'Salary':[500000,35467,23453]
})
df3['Initials']=df3['Name'].map(lambda x: ''.join([i[2] for i in x.split()]))
df3

          Name  Age  Salary Initials
0  Ajay Mishra   20  500000       as
1        Vijay   25   35467        j
2          Jay   50   23453        y

In [36]:
df4=pd.DataFrame({
    'A':[1,2,3],
    'B':[40,50,60]
})

In [37]:
df4_standardised=df4.transform(lambda x : (x-x.mean())/x.std())
df4_standardised

     A    B
0 -1.0 -1.0
1  0.0  0.0
2  1.0  1.0

In [38]:
print(df4_standardised)

     A    B
0 -1.0 -1.0
1  0.0  0.0
2  1.0  1.0