In [22]:
import pandas as pd

In [2]:
student={
    "rollno":[101,102,103,104,105],
    "name":['raj','ravi','riya','hardik','tanvi'],
    "age":[20,22,21,23,22],
    'gender':['male','male','male','male','female'],
    "city":['indore','satna','katni','indore','maihar']
    
}

In [3]:
df=pd.DataFrame(student)
df

   rollno    name  age  gender    city
0     101     raj   20    male  indore
1     102    ravi   22    male   satna
2     103    riya   21    male   katni
3     104  hardik   23    male  indore
4     105   tanvi   22  female  maihar

In [4]:
print(df)

   rollno    name  age  gender    city
0     101     raj   20    male  indore
1     102    ravi   22    male   satna
2     103    riya   21    male   katni
3     104  hardik   23    male  indore
4     105   tanvi   22  female  maihar

In [5]:
print(df['city'])

0    indore
1     satna
2     katni
3    indore
4    maihar
Name: city, dtype: object

In [6]:
print(df.iloc[0])

rollno       101
name         raj
age           20
gender      male
city      indore
Name: 0, dtype: object

In [7]:
df.iloc[:
        ]

   rollno    name  age  gender    city
0     101     raj   20    male  indore
1     102    ravi   22    male   satna
2     103    riya   21    male   katni
3     104  hardik   23    male  indore
4     105   tanvi   22  female  maihar

In [8]:
df.iloc[1]

rollno      102
name       ravi
age          22
gender     male
city      satna
Name: 1, dtype: object

In [9]:
df['name']

0       raj
1      ravi
2      riya
3    hardik
4     tanvi
Name: name, dtype: object

In [10]:
df["grade"]=['A','B','C','D','E']

In [11]:
df

   rollno    name  age  gender    city grade
0     101     raj   20    male  indore     A
1     102    ravi   22    male   satna     B
2     103    riya   21    male   katni     C
3     104  hardik   23    male  indore     D
4     105   tanvi   22  female  maihar     E

In [12]:
df[['rollno','name',"age"]]

   rollno    name  age
0     101     raj   20
1     102    ravi   22
2     103    riya   21
3     104  hardik   23
4     105   tanvi   22

In [13]:
employee={
    "emp_id":[101,102,103,104,105],
    "first_name":['raj','ravi','riya','hardik','harry'],
    "last_name":['jain','soni','singh','mishra','tiwari'],
    "department":['HR','IT','IT','SALES','ACCOUNT'],
    'salary':[100000,200000,300000,10000,210000]
}
df1=pd.DataFrame(employee)
df1

   emp_id first_name last_name department  salary
0     101        raj      jain         HR  100000
1     102       ravi      soni         IT  200000
2     103       riya     singh         IT  300000
3     104     hardik    mishra      SALES   10000
4     105      harry    tiwari    ACCOUNT  210000

In [14]:
df1['salary'].sum()

np.int64(820000)

In [15]:
df1['salary']

0    100000
1    200000
2    300000
3     10000
4    210000
Name: salary, dtype: int64

In [16]:
df1['salary'].min()

np.int64(10000)

In [17]:
df1['salary'].max()

np.int64(300000)

In [18]:
df1['salary'].var()

np.float64(12430000000.0)

In [19]:
df1['salary'].std()

np.float64(111489.90985734988)

In [20]:
df1['salary'].mean(
    
)

np.float64(164000.0)

In [21]:
df1.loc[0:2,['first_name','salary']]

  first_name  salary
0        raj  100000
1       ravi  200000
2       riya  300000