In [2]:
import pandas as pd

In [3]:
ind=['a','b','c','d','e']
emp={
    'emp_id':[101,102,103,104,105],
    "name":['raj','ravi','riya','hardik','harry'],
    'age':[26,25,27,25,28],
    'salary':[100000,200000,300000,10000,210000]
}

In [4]:
df=pd.DataFrame(emp,index=ind)
df

   emp_id    name  age  salary
a     101     raj   26  100000
b     102    ravi   25  200000
c     103    riya   27  300000
d     104  hardik   25   10000
e     105   harry   28  210000

In [5]:
df.iloc[0]

emp_id       101
name         raj
age           26
salary    100000
Name: a, dtype: object

In [8]:
df.loc['a']

emp_id       101
name         raj
age           26
salary    100000
Name: a, dtype: object

In [18]:
df.iloc[0:2,[0,1,2,3]]

   emp_id  name  age  salary
a     101   raj   26  100000
b     102  ravi   25  200000

In [22]:
s=df['salary']
print(s)
s.sum()

a    100000
b    200000
c    300000
d     10000
e    210000
Name: salary, dtype: int64

np.int64(820000)

In [23]:
s.min()

np.int64(10000)

In [24]:
s.var()

np.float64(12430000000.0)

In [25]:
s.std()

np.float64(111489.90985734988)

In [26]:
age=df['age']

In [27]:
age

a    26
b    25
c    27
d    25
e    28
Name: age, dtype: int64

In [28]:
age.min()

np.int64(25)

In [29]:
age.max()

np.int64(28)

In [30]:
age.var()

np.float64(1.7000000000000002)

In [31]:
age.mean()

np.float64(26.2)

In [32]:
sal_age=df[['age','salary']]

In [33]:
sal_age

   age  salary
a   26  100000
b   25  200000
c   27  300000
d   25   10000
e   28  210000

In [34]:
sal_age.sum()

age          131
salary    820000
dtype: int64

In [35]:
sal_age.min()

age          25
salary    10000
dtype: int64

In [36]:
sal_age.mean()

age           26.2
salary    164000.0
dtype: float64

In [37]:
sal_age.std()

age            1.303840
salary    111489.909857
dtype: float64

In [38]:
sal_age.var()

age       1.700000e+00
salary    1.243000e+10
dtype: float64

In [40]:
sal_age.max()

age           28
salary    300000
dtype: int64

In [41]:
df.head(0)

Empty DataFrame
Columns: [emp_id, name, age, salary]
Index: []

In [46]:
df.head(5)

   emp_id    name  age  salary
a     101     raj   26  100000
b     102    ravi   25  200000
c     103    riya   27  300000
d     104  hardik   25   10000
e     105   harry   28  210000

In [47]:
df.head(2)

   emp_id  name  age  salary
a     101   raj   26  100000
b     102  ravi   25  200000

In [51]:
df.head(10)

   emp_id    name  age  salary
a     101     raj   26  100000
b     102    ravi   25  200000
c     103    riya   27  300000
d     104  hardik   25   10000
e     105   harry   28  210000

In [52]:
df.head(0)

Empty DataFrame
Columns: [emp_id, name, age, salary]
Index: []

##head important hai

df.to_csv('employee.csv)

In [54]:
# df.to_csv('employee.csv')