In [2]:
import pandas as pd

In [14]:
df=pd.read_csv('employee.csv')
df.head(0)

Empty DataFrame
Columns: [emp_id, name, age, salary]
Index: []

In [15]:
new_df=df[['emp_id','age','salary','name']]
new_df

   emp_id  age  salary    name
0     101   26  100000     raj
1     102   25  200000    ravi
2     103   27  300000    riya
3     104   25   10000  hardik
4     105   28  210000   harry
5     106   24  173000  RAVISH
6     107   26  176000    jaki
7     108   27  179000  kumari
8     109   28  182000  hariom
9     110   29  185000    kalu

In [16]:
new_df.head(2)

   emp_id  age  salary  name
0     101   26  100000   raj
1     102   25  200000  ravi

In [17]:
new_df.head(2)

   emp_id  age  salary  name
0     101   26  100000   raj
1     102   25  200000  ravi

In [18]:
new_df['ta']=new_df['salary']*0.16

C:\Users\nepro\AppData\Local\Temp\ipykernel_20052\2561510675.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['ta']=new_df['salary']*0.16

In [19]:
new_df['da']=new_df['salary']*0.20

C:\Users\nepro\AppData\Local\Temp\ipykernel_20052\2843137956.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['da']=new_df['salary']*0.20

In [20]:
new_df

   emp_id  age  salary    name       ta       da
0     101   26  100000     raj  16000.0  20000.0
1     102   25  200000    ravi  32000.0  40000.0
2     103   27  300000    riya  48000.0  60000.0
3     104   25   10000  hardik   1600.0   2000.0
4     105   28  210000   harry  33600.0  42000.0
5     106   24  173000  RAVISH  27680.0  34600.0
6     107   26  176000    jaki  28160.0  35200.0
7     108   27  179000  kumari  28640.0  35800.0
8     109   28  182000  hariom  29120.0  36400.0
9     110   29  185000    kalu  29600.0  37000.0

In [21]:
new_df['department']=['HR','IT','SALES','FINANCE','ACCOUNTS','IT','IT','SALES','FINANCE','IT']

C:\Users\nepro\AppData\Local\Temp\ipykernel_20052\1369488333.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['department']=['HR','IT','SALES','FINANCE','ACCOUNTS','IT','IT','SALES','FINANCE','IT']

In [25]:
new_df['gross_salary']=new_df['salary']+new_df['ta']+new_df['da']

C:\Users\nepro\AppData\Local\Temp\ipykernel_20052\2759409364.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['gross_salary']=new_df['salary']+new_df['ta']+new_df['da']

In [26]:
new_df.head(0)

Empty DataFrame
Columns: [emp_id, age, salary, name, ta, da, department, gross_salary]
Index: []

In [ ]:
# new_df.to_csv("employee2.csv",index=False)

In [29]:
new_df['tax']=new_df['gross_salary']*0.05

C:\Users\nepro\AppData\Local\Temp\ipykernel_20052\2734299188.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tax']=new_df['gross_salary']*0.05

In [30]:
new_df.head(11)

,emp_id,age,salary,name,ta,da,department,gross_salary,tax
0,101,26,100000,raj,16000.0,20000.0,HR,136000.0,6800.0
1,102,25,200000,ravi,32000.0,40000.0,IT,272000.0,13600.0
2,103,27,300000,riya,48000.0,60000.0,SALES,408000.0,20400.0
3,104,25,10000,hardik,1600.0,2000.0,FINANCE,13600.0,680.0
4,105,28,210000,harry,33600.0,42000.0,ACCOUNTS,285600.0,14280.0
5,106,24,173000,RAVISH,27680.0,34600.0,IT,235280.0,11764.0
6,107,26,176000,jaki,28160.0,35200.0,IT,239360.0,11968.0
7,108,27,179000,kumari,28640.0,35800.0,SALES,243440.0,12172.0
8,109,28,182000,hariom,29120.0,36400.0,FINANCE,247520.0,12376.0
9,110,29,185000,kalu,29600.0,37000.0,IT,251600.0,12580.0

In [31]:
new_df['actual_salary']=new_df['gross_salary']-new_df['tax']

C:\Users\nepro\AppData\Local\Temp\ipykernel_20052\24397895.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['actual_salary']=new_df['gross_salary']-new_df['tax']

In [32]:
new_df.head(11)

,emp_id,age,salary,name,ta,da,department,gross_salary,tax,actual_salary
0,101,26,100000,raj,16000.0,20000.0,HR,136000.0,6800.0,129200.0
1,102,25,200000,ravi,32000.0,40000.0,IT,272000.0,13600.0,258400.0
2,103,27,300000,riya,48000.0,60000.0,SALES,408000.0,20400.0,387600.0
3,104,25,10000,hardik,1600.0,2000.0,FINANCE,13600.0,680.0,12920.0
4,105,28,210000,harry,33600.0,42000.0,ACCOUNTS,285600.0,14280.0,271320.0
5,106,24,173000,RAVISH,27680.0,34600.0,IT,235280.0,11764.0,223516.0
6,107,26,176000,jaki,28160.0,35200.0,IT,239360.0,11968.0,227392.0
7,108,27,179000,kumari,28640.0,35800.0,SALES,243440.0,12172.0,231268.0
8,109,28,182000,hariom,29120.0,36400.0,FINANCE,247520.0,12376.0,235144.0
9,110,29,185000,kalu,29600.0,37000.0,IT,251600.0,12580.0,239020.0

In [33]:
# new_sum=new_df[['ta','da','gross_salary','tax','actual_salary']]

In [44]:
tot_sal=new_df['salary'].sum()

In [45]:
tot_ta=new_df['ta'].sum()
tot_da=new_df['da'].sum()
tot_gross=new_df['gross_salary'].sum()
tot_tax=new_df['tax'].sum()
tot_actual=new_df['actual_salary'].sum()

In [47]:
print("total salary : ",tot_sal)
print("total ta :",tot_ta)
print("total da : ",tot_da)
print("total gross salary : ",tot_gross)
print("total tax : ",tot_tax)
print("total actual salary : ",tot_actual)

total salary :  1715000
total ta : 274400.0
total da :  343000.0
total gross salary :  2332400.0
total tax :  116620.0
total actual salary :  2215780.0