In [3]:
import pandas as pd 
from sqlalchemy import create_engine

In [4]:
con_string="mysql+pymysql://root:0000@localhost:3306/pd_db"
engine=create_engine(con_string)

In [7]:
query='select * from student'
df=pd.read_sql(query,con=engine)
df

   rollno    name   age  gender    city
0   101.0     raj  20.0    male  indore
1   102.0    ravi  22.0    male   satna
2   103.0    riya  21.0    male   katni
3   104.0  hardik   NaN    male    None
4     NaN   tanvi  22.0  female  maihar

In [10]:
query="select * from student where city='indore' "  
df1=pd.read_sql(query,con=engine)
df1

   rollno name   age gender    city
0   101.0  raj  20.0   male  indore

In [12]:
query="select * from student where gender='male' "  
df2=pd.read_sql(query,con=engine)
df2

   rollno    name   age gender    city
0   101.0     raj  20.0   male  indore
1   102.0    ravi  22.0   male   satna
2   103.0    riya  21.0   male   katni
3   104.0  hardik   NaN   male    None

In [13]:
df=pd.read_csv("student.csv")
df

   rollno    name   age  gender    city
0   101.0     raj  20.0    male  indore
1   102.0    ravi  22.0    male   satna
2   103.0    riya  21.0    male   katni
3   104.0  hardik   NaN    male     NaN
4     NaN   tanvi  22.0  female  maihar

In [14]:
df=pd.read_excel("student.xlsx")
df

   rollno    name   age  gender    city
0   101.0     raj  20.0    male  indore
1   102.0    ravi  22.0    male   satna
2   103.0    riya  21.0    male   katni
3   104.0  hardik   NaN    male     NaN
4     NaN   tanvi  22.0  female  maihar

In [15]:
df=pd.read_html("student.html")
df

[   rollno    name   age  gender    city
 0   101.0     raj  20.0    male  indore
 1   102.0    ravi  22.0    male   satna
 2   103.0    riya  21.0    male   katni
 3   104.0  hardik   NaN    male     NaN
 4     NaN   tanvi  22.0  female  maihar]

In [16]:
df=pd.read_json("student.json")
df

   rollno    name   age  gender    city
0   101.0     raj  20.0    male  indore
1   102.0    ravi  22.0    male   satna
2   103.0    riya  21.0    male   katni
3   104.0  hardik   NaN    male    None
4     NaN   tanvi  22.0  female  maihar

In [19]:
df=pd.read_csv("employee2.csv")
df.to_json("employee2.json")

In [20]:
df

Empty DataFrame
Columns: [{"emp_id":{"0":101, 1:102, 2:103, 3:104, 4:105, 5:106, 6:107, 7:108, 8:109, 9:110}, age:{"0":26, 1:25, 2:27, 3:25, 4:28, 5:24, 6:26, 7:27, 8:28, 9:29}, salary:{"0":100000, 1:200000, 2:300000, 3:10000, 4:210000, 5:173000, 6:176000, 7:179000, 8:182000, 9:185000}, name:{"0":"raj", 1:"ravi", 2:"riya", 3:"hardik", 4:"harry", 5:"RAVISH", 6:"jaki", 7:"kumari", 8:"hariom", 9:"kalu"}, ta:{"0":16000, 1:32000, 2:48000, 3:1600, 4:33600, 5:27680, 6:28160, 7:28640, 8:29120, 9:29600}, da:{"0":20000, 1:40000, 2:60000, 3:2000, 4:42000, 5:34600, 6:35200, 7:35800, 8:36400, 9:37000}, department:{"0":"HR", 1:"IT", 2:"SALES", 3:"FINANCE", 4:"ACCOUNTS", 5:"IT", 6:"IT", 7:"SALES", 8:"FINANCE", 9:"IT"}, gross_salary:{"0":136000, 1:272000, 2:408000, 3:13600, 4:285600, 5:235280, 6:239360, 7:243440, 8:247520, 9:251600}}]
Index: []

[0 rows x 80 columns]