In [2]:
import pandas as pd 
from sqlalchemy import create_engine

In [3]:
con_string="mysql+pymysql://root:0000@localhost:3306/pd_db"
engine=create_engine(con_string)

In [4]:
df=pd.read_csv('formula1.csv')
df

    CustomerCode  CustomerName  Country   Age  Product   Amount        Year
0           1001       Adorjan      USA    37    Shoes      500    5/1/2016
1           1002          Arun    Nepal    28    Shirt      300  14-01-2016
2           1003         Sumit    India    32      Cap      250  29-01-2016
3           1004      Benjamin      USA    41    Shoes      500   12/2/2016
4           1005        Ganesh    Nepal    30    Shirt      300  22-02-2016
..           ...           ...      ...   ...      ...      ...         ...
95          1096     Goverdhan    Nepal    36      Cap      250  30-04-2019
96          1097        Jayala      USA    28    Shoes      500    1/5/2019
97          1098      Ravindra    India    35    Shirt      300    2/5/2019
98          1099        Gopal    Nepal     38      Cap      250    5/7/2019
99          1006        Ashish    India    35      Cap      200    2/3/2016

[100 rows x 7 columns]

In [5]:
df.head(0)

Empty DataFrame
Columns: [CustomerCode,  CustomerName,  Country,  Age,  Product,  Amount, Year]
Index: []

In [6]:
df.dropna()

    CustomerCode  CustomerName  Country   Age  Product   Amount        Year
0           1001       Adorjan      USA    37    Shoes      500    5/1/2016
1           1002          Arun    Nepal    28    Shirt      300  14-01-2016
2           1003         Sumit    India    32      Cap      250  29-01-2016
3           1004      Benjamin      USA    41    Shoes      500   12/2/2016
4           1005        Ganesh    Nepal    30    Shirt      300  22-02-2016
..           ...           ...      ...   ...      ...      ...         ...
95          1096     Goverdhan    Nepal    36      Cap      250  30-04-2019
96          1097        Jayala      USA    28    Shoes      500    1/5/2019
97          1098      Ravindra    India    35    Shirt      300    2/5/2019
98          1099        Gopal    Nepal     38      Cap      250    5/7/2019
99          1006        Ashish    India    35      Cap      200    2/3/2016

[100 rows x 7 columns]

In [7]:
df.to_sql('amount',if_exists='replace',con=engine,index=False)

100